name = "waffle's Modpack"
author = "triphora"
version = "2023.09.17"
description = "Highly customizable rolling-release client-side pack compatible with any multiplayer server, focusing on performance and features that still feel true to vanilla."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c90acbdd2ea2cc7d48b2f0ba34e8de7269df0fc0024f170dbe5b8084a910303"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.20"]
